name: "🐣 Enhancement"
description: "새로운 기능 추가"
title : "[MOVIE/MEMBER]"
labels: ["🐣 enhancement"]
projects: ["beyond-SW-Camp-14th-5rE5/2"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 최대한 자세하게 작성해 주세요!
      value:
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해 주세요.
      placeholder: 최대한 세분화해서 적어 주세요!
      value:
    validations:
      required: true
